### ISSUE TITLE
Unable to import CT openapi.yaml file onto our Azure APIM 

### ISSUE THREAD

**Issue by okuppurajah** [commercetools/commercetools-api-reference#279]
Attached is the error generated while importing the openapi spec into our Azure APIM.
May be i am missing some things, kindly review and help.
[Import errors.txt](https://github.com/commercetools/commercetools-api-reference/files/10384770/Import.errors.txt)

**Comment by jenschude** [comment]
Sorry for the inconvenience.

I identified a typo in the generator for the openapi files and fixed it. Will trigger an update once it's published.

**Comment by jenschude** [comment]
Fixed with ec79a6a

**Comment by okuppurajah** [comment]
H,
i tried the import this morning. I still get some parsing issues. This time the parsing error is less. I believe you fixed majority of the issue.
But still seeing few errors. Attached
[Import errors_2.txt](https://github.com/commercetools/commercetools-api-reference/files/10394432/Import.errors_2.txt)

**Comment by jenschude** [comment]
Man openapi is really strange. The swagger-cli said it's valid. Taking a look.

**Comment by jenschude** [comment]
Can you please check again?

**Comment by okuppurajah** [comment]
Hi, those errors seems to have gone. I have the following response with the most recent file.

One or more fields contain incorrect values:
Parsing error(s): Schema ResourceIdentifier must contain property specified in the discriminator typeId in the required field list. [#/components/schemas/ResourceIdentifier/discriminator]
Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).
One or more fields contain incorrect values:;Parsing error(s): Schema ResourceIdentifier must contain property specified in the discriminator typeId in the required field list. [#/components/schemas/ResourceIdentifier/discriminator];Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification <a target="_blank" href="https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md">https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md</a> (schema <a target="_blank" href="https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml">https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml</a>).


![image](https://user-images.githubusercontent.com/122386808/213011043-a9060636-aaee-4c06-9d7a-3071810ad943.png)

**Comment by jenschude** [comment]
Hrm. I can fix it, but it should be correct as the `typeId` field references a String type with an enum definition. Will take a look how to solve this.

**Comment by okuppurajah** [comment]
any update on this issue ?

**Comment by jenschude** [comment]
Fixed it. And also ran it once through the autorest azure validator and only reported warnings now.

**Comment by jenschude** [comment]
The openapi definitions are now validated against the azure validator on every update.
